const Data = [
  {
    user_name: "급발진간다",
    ranking: "650,888",
    tier: "platinum",
    tier_num: 4,
    point: 0,
    win: 140,
    lose: 114,
    match_list: [
      {
        result: "win",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "lose",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "lose",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "lose",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "샤코",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
    ],
  },
];

export default Data;
