const Data = [
  {
    user_name: "급발진간다",
    user_info: {
      ranking: "650,888",
      tier: "Platinum",
      tier_num: 4,
      point: 0,
      win: 140,
      lose: 114,
    },
    match_list: [
      {
        result: "lose",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 16,
        cs: 109,
        kill: 3,
        death: 14,
        assist: 2,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 239,
        kill: 10,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 149,
        kill: 3,
        death: 4,
        assist: 6,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 12,
        cs: 39,
        kill: 1,
        death: 1,
        assist: 1,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 17,
        cs: 160,
        kill: 13,
        death: 24,
        assist: 16,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 300,
        kill: 31,
        death: 10,
        assist: 6,
      },
      {
        result: "lose",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 149,
        kill: 3,
        death: 2,
        assist: 16,
      },
      {
        result: "lose",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 167,
        kill: 13,
        death: 4,
        assist: 16,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 63,
        kill: 31,
        death: 1,
        assist: 2,
      },
      {
        result: "win",
        champion: "Shaco",
        spell1: "Ignite",
        spell2: "Exhaust",
        rune1: "Dark_Harvest_rune",
        rune2: "Precision",
        level: 20,
        cs: 149,
        kill: 11,
        death: 21,
        assist: 22,
      },
    ],
  },
];

export default Data;
